### ISSUE TITLE
Request for info about API support and counters/info for every API..

### ISSUE THREAD

**Issue by oscarbg** [intel/metrics-discovery#1]
Supports all the APIs below?
*OpenGL Mesa..
*Vulkan Anvil driver
*OpenCL Beignet and new Neo OpenCL driver
*libVA video encode/decode usage

What counters on every API?
Thanks..

**Comment by adatczuk** [comment]
Hi Oscar,

There are two types of measurements in Metrics Discovery:
- Timer mode which automatically generate samples in a specified cadence. This mode is API independent. It's based on i915_Perf.
- Query mode, in which user decides when to start/end the measurement, is currently supported only with OpenGL Mesa through INTEL_performance_query interface.

Counters availability depends on hardware used and chosen measurement mode. They're dynamically filtered in runtime and can be enumerated right after opening the library interface.

I hope this answers your question.

Regards,
Andrzej

**Comment by gabe2004** [comment]
Is MFX_Usage supported similar to what was provided in Intel PAL?

**Comment by huzaifasami25** [comment]
I need the list of performance counter queries used behind every metrics in Intel Analyzer.Can anyone guide me?
