### ISSUE TITLE
build: don't use self-defined cmake names for the existing things

### ISSUE THREAD

**Issue by dvrogozh** [intel/metrics-discovery#10]
Please, remove these 2 self-defined names required for the project build:
* MD_BUILD_TYPE (=release)
* MD_PLATFORM (=linux)

Instead use:
* CMAKE_BUILD_TYPE instead of MD_BUILD_TYPE
* CMAKE_SYSTEM_NAME instead of MD_PLATFORM

General rule: don't define self-names if the concept already exists. For example, defining MD_PLATFORM you step into issues with cross compiling which were already reported for media-drviver and mediasdk projects. If you need some other veriables to setup something, review https://cmake.org/Wiki/CMake_Cross_Compiling first.

Secondly, please, support default build configuration, i.e.:
`cmake ..`
You don't actually need to specify those 2 things you now require at all. You may wish to have a default for CMAKE_BUILD_TYPE as follows:
```
if(NOT CMAKE_BUILD_TYPE)
  message(STATUS "No build type selected, default to release")
  set(CMAKE_BUILD_TYPE release)
endif()
```

**Comment by dos1** [comment]
A small correction:
```cmake
if (NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
	message(STATUS "No build type selected, default to release")
	set(CMAKE_BUILD_TYPE Release)
endif (NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
```
Otherwise you're going to break multiconfiguration generators :)

**Comment by MaciejOlchowiczIntel** [comment]
Fixed in: https://github.com/intel/metrics-discovery/commit/13aed6579896f79edfbccb623c7c44a8baab61e3
