### ISSUE TITLE
MFX_USAGE?

### ISSUE THREAD

**Issue by gabe2004** [intel/metrics-discovery#12]
Is Mfx_usage supported similar to that in Intel PAL library?

**Comment by nityapurnima** [comment]
Downloaded and built the libmd.so. How should i use this library in my code to generate the GPU metrics.

Can someone please suggest list of MD API's and their usage to get the information about GPU Metrics like GPU usage, MFX usage, etc.

**Comment by nityapurnima** [comment]
Hi

Can you please tell me if their is any MD API to calculate the GPU usage metric.

Regards
Nitya

**Comment by adatczuk** [comment]
Hi Nitya,

Metrics Discovery API provides GpuBusy metric which represents "The percentage of time in which the GPU has been processing GPU commands."

Regards,
Andrzej

**Comment by nityapurnima** [comment]
Hi Andrzej,

I understand that GpuBusy metric calculates the time for processing the gpu commands but is their any MD API which represents the percentage of GPU Load of the particular application.

Regards,
Nitya

**Comment by adatczuk** [comment]
Hi Nitya,

Metrics Discovery returns ContextId for every report, so you can match it with a specific application.

Regards,
Andrzej

**Comment by nityapurnima** [comment]
Hi Andrzej

Thanks for your timely reply.
Can  you please help me in understanding the below points:

1. I found few metrics like Vdbox0, Vdbox1, VeboxBusy. Are these metrics similar to mfx_usage and mfx_decode or different?
Can i consider VeboxBusy measurements same for mfx measurements or they both are entirely different?

2. I have also downloaded opencl-intercept-layer-master and built it. It only creates a libOpenCl.so. Can you provide any application which uses MD api and on executing the application a report is generated. It will be helpful if you can share the report with me.

**Comment by nityapurnima** [comment]
Hi Andrzej

I would like to know if there is any linux command line argument to know veboxbusy metrics of a particular application.
For example:
sudo intel_gpu_time ./applic_executable
The above command gives the cpu and gpu usage of the application.
Similarly i need a linux command to know the veboxbusy of a particualr application.

Regards
Nitya

**Comment by adatczuk** [comment]
Hi Nitya,

Sorry for the late response. From what I know these metrics cover mfx but also other parts like hevc or vdenc. They shows the input queue occupancy to these blocks. Answering the question, if you use only mfx they could be the same, but in general they're not.
As for the application you're asking, currently we don't have such. Please contact Gabriel S. directly for more information.

Regards,
Andrzej
