### ISSUE TITLE
L3ShaderThroughput for SKL, KBL, CFL, BXT, GLK

### ISSUE THREAD

**Issue by skuka** [intel/metrics-discovery#15]
In the L3ShaderThroughput formulas for SKL, KBL, CFL, BXT, GLK there should be $$SlmBytesRead and $$SlmBytesWritten instead of $SlmBytesRead and $SlmBytesWritten.

**Comment by MaciejOlchowiczIntel** [comment]
Fixed in: https://github.com/intel-innersource/drivers.gpu.unified/commit/9ec1bf46781419d78880f1de6f0412808c896bff

**Comment by MaciejOlchowiczIntel** [comment]
Fixed in: https://github.com/intel/metrics-discovery/commit/da7f6523a914ddec0b760cb59f774e81daa6b929
