### ISSUE TITLE
how to reset TBS after application crash or abnormal exit?

### ISSUE THREAD

**Issue by bashbaug** [intel/metrics-discovery#18]
This issue is related to an issue filed by a user of the Intercept Layer for OpenCL Applications, which uses the metrics discovery features in Intel GPU drivers:

https://github.com/intel/opencl-intercept-layer/issues/141

In short, when an application that is using time-based sampling crashes, abnormally exits, or (as described in the issue) ends in a Visual Studio debugging session, there is no opportunity to shut down and close the the metrics library properly.  When the metrics library is not properly closed, time-based sampling remains enabled.  This prevents subsequent applications from using time-based sampling.  As best I can tell, there is no way to detect that this scenario has occurred or to recover from it.

Can the metrics library provide a mechanism to reset or recover in this scenario?  It would be nice if the recovery were performed automatically, but if there were a mechanism to detect this state and explicitly request recovery I think that would work too.

Thanks!

**Comment by mcleary** [comment]
Are there any updates on this?

**Comment by mcleary** [comment]
Are there any updates on this [2]?

**Comment by serge-s** [comment]
Try calling CloseMetricsDevice(nullptr) - you might need to do it more than once - see [CAdapter::CloseMetricsDevice](https://github.com/intel/metrics-discovery/blob/master/instrumentation/metrics_discovery/common/md_internal.cpp#L1392)

**Comment by bashbaug** [comment]
Hi @serge-s , can you say more how this should work?  Should `CloseMetricsDevice(nullptr)` be called in a loop until it no longer returns `CC_STILL_INITIALIZED`, and will this work even if another process initialized TBS?  Thanks!

**Comment by MaciejOlchowiczIntel** [comment]
In this case when you use:

- Windows you need to call function: IAdapter_1_6::Reset()
- Linux - This is handled with i915 internally

**Comment by bashbaug** [comment]
Hi, sorry, I still have follow-on questions:

* When should I call `IAdapter_1_6::Reset()`?  See questions above - will this still work if another process initialized TBS?
* Can I also call `IAdapter_1_6::Reset()` on Linux, or should this be on Windows only?

**Comment by RobertKrzemien** [comment]
* `IAdapter_1_6::Reset()` is useful when an application crashed and left TBS in the initialized state. The call checks if PID that opened TBS still exists, if not, TBS is closed and the next application can use TBS. This should be called before `OpenMetricsDevice` to ensure the previous application didn't leave TBS in the initialized state.
* `IAdapter_1_6::Reset()` is helpful on Windows only. Linux closes TBS if a process using TBS crashes.

**Comment by bashbaug** [comment]
* Thanks, this is helpful.  It would be nicer if `OpenMetricsDevice` would do the resetting automatically if the PID no longer exists so MDAPI users wouldn't need to make any additional calls, but I think I can make this work.
* Is it valid to call `IAdapter_1_6::Reset()` on Linux also, even if it is unnecessary?  Or do I need to add `#ifdefs` to call it only on Windows?

**Comment by RobertKrzemien** [comment]
* I have just remembered an improvement in the driver. On `OpenIoStream` kernel mode driver checks if TBS is initialized and the owner of TBS (a process) still exists. If not, TBS is reinitialized and the owner is set to the current process. So, the problem from the original issue (https://github.com/intel/opencl-intercept-layer/issues/141) should not happen anymore. But if there are still some issues with MDAPI, `IAdapter_1_6::Reset()` comes in very handy.
* `IAdapter_1_6::Reset()` does nothing on Linux. It just returns `TCompletionCode::CC_OK`. `#ifdefs` are not necessary.
