### ISSUE TITLE
Support for iHD drivers

### ISSUE THREAD

**Issue by fredvb** [intel/metrics-discovery#19]
All instructions for VTune point to enabling CONFIG_DRM_I915_LOW_LEVEL_TRACEPOINTS . 
This doesn't seem like something that would work on a device that has iHD drivers installed from intel-media-driver

**Comment by MaciejOlchowiczIntel** [comment]
We do not support CONFIG_DRM_I915_LOW_LEVEL_TRACEPOINTS. In case of further uncertainty, we suggest you write here:
https://community.intel.com/t5/Analyzers/bd-p/analyzers
