### ISSUE TITLE
Provide some simple sample using the API?

### ISSUE THREAD

**Issue by oscarbg** [intel/metrics-discovery#2]
Hi,
maybe good providing a simple sample of integrating this metrics API on a graphics/compute (OpenGL/OpenCL) app..
For ex. a OpenGL draw a single triangle app would be nice..

**Comment by adatczuk** [comment]
Hi Oscar,

Thank you for your suggestion. We are definitely thinking about it, I'm pretty sure you can expect API usage samples to appear in the future.

Regards,
Andrzej
