### ISSUE TITLE
CMake warning metrics discovery interface library is not found.

### ISSUE THREAD

**Issue by YMont** [intel/metrics-discovery#25]
Hi all,

I use Intel tool gpuinfo which will use Metrics Discovery library. 
And I follow the build and compile tutorial, I'm sure that I have already installed metrics discovery.
(Intel tool gpuinfo reference: https://github.com/intel/pti-gpu/tree/master/tools/gpuinfo)

**But why I execute gpuinfo it doesn't show anything?
And it show hint that Metrics Discovery Application Programming Interface library is not found.
I don't know how to fix it.**

OS:Ubuntu 22.04 (Linux kernel: 5.19.0-41)
CPU: i3-9100E (Coffee lake)
GPU: UHD Graphics 630

`test@test:~/pti-gpu/tools/gpuinfo/build$ cmake -DCMAKE_BUILD_TYPE=Release ..`
```
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build Type: Relase
-- Bitness: 64 bits
-- Looking for C++ include metrics_discovery_api.h
-- Looking for C++ include metrics_discovery_api.h - found
CMake Warning at /home/test/pti-gpu/build_utils/CMakeLists.txt:339 (message):
  Intel(R) Metrics Discovery Application Programming Interface library is not
  found.  You may need to install it to fix this issue.
Call Stack (most recent call first):
  CMakeLists.txt:23 (CheckForMDLibrary)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/pti-gpu/tools/gpuinfo/build
```

`test@test:~/pti-gpu/tools/gpuinfo/build$ make`
```
[ 50%] Building CXX object CMakeFiles/gpuinfo.dir/main.cc.o
[100%] Linking CXX executable gpuinfo
[100%] Built target gpuinfo
```
`test@test:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -l`
```Unable to find GPU devices```
`test@test:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -i`
```Unable to find GPU devices```

Thanks a lot.
Best regards,

**Comment by RobertKrzemien** [comment]
Hi,

PTI is trying to load libmd.so: https://github.com/intel/pti-gpu/blob/master/utils/metric_utils.h#L34
But Metrics Discovery library is lib**igd**md.so. Please change the name and see if it fixes your issue.

To fix CMake warning, you need to change "md" to "igdmd" at line: https://github.com/intel/pti-gpu/blob/master/build_utils/CMakeLists.txt#L336

**Comment by YMont** [comment]
Hi RobertKrzemien,

Thanks for your advice. It works.
But I got the new problem.

`test@AX:~/pti-gpu/tools/gpuinfo/build$ cmake -DCMAKE_BUILD_TYPE=Release ..`
```
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build Type: Release
-- Bitness: 64 bits
-- Looking for C++ include metrics_discovery_api.h
-- Looking for C++ include metrics_discovery_api.h - found
-- Intel(R) Metrics Discovery Application Programming Interface library is found at /usr/lib/x86_64-linux-gnu/libigdmd.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/pti-gpu/tools/gpuinfo/build
```

`test@AX:~/pti-gpu/tools/gpuinfo/build$ make`
```
[ 50%] Building CXX object CMakeFiles/gpuinfo.dir/main.cc.o
[100%] Linking CXX executable gpuinfo
[100%] Built target gpuinfo
```
---

**New issue**
```
Usage: ./gpuinfo[.exe] <options>
Options:
-l        Print list of available devices
-i        Print general device info
-m        Print list of available mertrics
-h        Print this help message
```
`test@AX:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -l`
```
gpuinfo: /home/test/pti-gpu/tools/gpuinfo/../../utils/metric_device.h:33: static uint32_t MetricDevice::GetDeviceCount(): Assertion `status == md::CC_OK' failed.
Aborted (core dumped)
```
`test@AX:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -i`
Device 0:
gpuinfo: /home/test/pti-gpu/tools/gpuinfo/../../utils/metric_device.h:53: static uint32_t MetricDevice::GetSubDeviceCount(uint32_t): Assertion `status == md::CC_OK' failed.
Aborted (core dumped)
```
What does it means about **status == md::CC_OK failed**?

Thanks a lot.
Best regards,

**Comment by YMont** [comment]
Hi RobertKrzemien,

@RobertKrzemien As the following are my devices.
Device 1-
CPU: i3-9100E(Coffee Lake)
GPU: Intel(R) UHD Graphics 630(GFL GT2)
OS: Ubuntu 22.04
Linux Kernel: 5.19.0-4-generic

Device 2-
CPU: i5-8500(coffee Lake)
GPU: Intel(R) Graphics(Coffeelake 3x8 GT2)
OS: Ubuntu 18.04
Linux Kernel: 4.15.0-136-generic

---
`PTI_ASSERT(status == md::CC_OK || status == md::CC_ALREADY_INITIALIZED);`
It works.

I replace all over `PTI_ASSERT(status == md::CC_OK);` to `CC_ALREADY_INITIALIZED`.
Besides, only `<pti-gpu>/utils/metric_device.h  line:121` can't use this method and compile error. 
Therefore, I comment this line. But I don't that am I correct about giving comment in line 121 straightly?
After compiling, I think that is successful.

`test@test:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -l`
```
Device 0: /dev/dri/renderD128
```

`test@test:~/pti-gpu/tools/gpuinfo/build$ ./gpuinfo -i`
```
Device 0:
---- Name: /dev/dri/renderD128
---- GpuTimestampFrequency: 12000000
---- NumberOfShadingUnits: 28
---- NumberOfRenderOutputUnits: 4
---- ApertureSize: 0
---- GpuCurrentFrequencyMHz: 350
---- GtSubsliceMask: unknown
---- PlatformIndex: 18
---- GtSlice0Subslice1: true
---- GtSlice0: true
---- GtSliceMask: unknown
---- OABufferMaxSize: 16777216
---- SubsliceMask: 7
---- OABufferMinSize: 16777216
---- GpuMinFrequencyMHz: 350
---- SliceMask: 1
---- EuThreadsCount: 7
---- PciDeviceId: 3e98
---- GtSlice0Subslice2: true
---- GtSlice0Subslice0: true
---- EuSlicesTotalCount: 1
---- MaxTimestamp: 357913941250
---- SkuRevisionId: 2
---- EuSubslicesTotalCount: 3
---- GpuMaxFrequencyMHz: 1050
---- EuCoresPerSubsliceCount: 7
---- SamplersTotalCount: 3
---- EuCoresTotalCount: 23
```
Thanks a lot.
Best regards,
